services:
  influxdb:
    image: influxdb:latest
    container_name: influxdb
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=${DOCKER_INFLUXDB_INIT_USERNAME}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${DOCKER_INFLUXDB_INIT_PASSWORD}
      - DOCKER_INFLUXDB_INIT_ORG=${INFLUXDB_ORG}
      - DOCKER_INFLUXDB_INIT_BUCKET=${INFLUXDB_BUCKET}
      - DOCKER_INFLUXDB_INIT_RETENTION=0
    volumes:
      - influxdb-data:/var/lib/influxdb
      - influxdb-ssl:/etc/ssl/influxdb
    networks:
      - private-network
    ports:
      - "8086:8086"  # API Port
    restart: unless-stopped

  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    volumes:
      - grafana-storage:/var/lib/grafana
    networks:
      - private-network
    restart: unless-stopped

  caddy:
    image: caddy:latest
    container_name: caddy
    ports:
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
    networks:
      - private-network
    restart: unless-stopped

  feeder:
    image: php:8.3-cli-alpine
    container_name: feeder
    volumes:
      - ./icecast.php:/icecast.php
    environment:
      - ICECAST_URL=${ICECAST_URL}
      - ICECAST_HOST=${ICECAST_HOST}
      - ICECAST_USERNAME=${ICECAST_USERNAME}
      - ICECAST_PASSWORD=${ICECAST_PASSWORD}
      - INFLUXDB_URL=${INFLUXDB_URL}
      - INFLUXDB_TOKEN=${INFLUXDB_TOKEN}
      - INFLUXDB_ORG=${INFLUXDB_ORG}
      - INFLUXDB_BUCKET=${INFLUXDB_BUCKET}
      - INFLUXDB_PRECISION=${INFLUXDB_PRECISION}
    networks:
      - private-network
    command: php /icecast.php
    restart: unless-stopped

volumes:
  influxdb-data:
    driver: local
  influxdb-ssl:
    driver: local
  grafana-storage:
    driver: local

networks:
  private-network:
    driver: bridge
