services:
  influxdb:
    image: influxdb:latest
    container_name: influxdb
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=${DOCKER_INFLUXDB_INIT_USERNAME}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${DOCKER_INFLUXDB_INIT_PASSWORD}
      - DOCKER_INFLUXDB_INIT_ORG=${INFLUXDB_ORG}
      - DOCKER_INFLUXDB_INIT_BUCKET=${INFLUXDB_BUCKET}
      - DOCKER_INFLUXDB_INIT_RETENTION=0
    volumes:
      - influxdb-data:/var/lib/influxdb
      - influxdb-ssl:/etc/ssl/influxdb
    networks:
      - private-network
    ports:
      - "8086:8086"  # API Port

  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    volumes:
      - grafana-storage:/var/lib/grafana
    networks:
      - private-network

  caddy:
    image: caddy:latest
    container_name: caddy
    ports:
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
    networks:
      - private-network

volumes:
  influxdb-data:
    driver: local
  influxdb-ssl:
    driver: local
  grafana-storage:
    driver: local

networks:
  private-network:
    driver: bridge
