version: '3.8'

services:
  influxdb:
    image: influxdb:latest
    container_name: influxdb
    environment:
      - INFLUXDB_HTTP_AUTH_ENABLED=true
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=hackme
    volumes:
      - influxdb-data:/var/lib/influxdb
      - influxdb-ssl:/etc/ssl/influxdb
    networks:
      - private-network

  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    volumes:
      - grafana-storage:/var/lib/grafana
    networks:
      - private-network

  caddy:
    image: caddy:latest
    container_name: caddy
    ports:
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
    networks:
      - private-network

volumes:
  influxdb-data:
    driver: local
  influxdb-ssl:
    driver: local
  grafana-storage:
    driver: local

networks:
  private-network:
    driver: bridge
