{
 "title": "Alle mountpoints",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Alle mountpoints",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "alias": "/radiorucphen.mp3",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "icecast2",
     "query": "from(bucket: \"icecast\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"listeners\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"example-host\")\r\n  |> filter(fn: (r) => r[\"mount\"] == \"/radiorucphen.aac\" or r[\"mount\"] == \"/radiorucphen.mp3\" or r[\"mount\"] == \"/zuidwest.aac\" or r[\"mount\"] == \"/zuidwest.mp3\" or r[\"mount\"] == \"/zuidwest.stl\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")",
     "select": [
      [
       { "params": [ "listeners" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "media1" },
      { "condition": "AND", "key": "mount", "operator": "=", "value": "/radiorucphen.mp3" }
     ]
    },
    {
     "alias": "/radiorucphen.aac",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "icecast2",
     "select": [
      [
       { "params": [ "listeners" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "media1" },
      { "condition": "AND", "key": "mount", "operator": "=", "value": "/radiorucphen.aac" }
     ]
    }
   ]
  },
  {
   "title": "radiorucphen.mp3",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "query": "from(bucket: \"icecast\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"listeners\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"example-host\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> filter(fn: (r) => r[\"mount\"] == \"/radiorucphen.mp3\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "radiorucphen.aac",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {
     "query": "from(bucket: \"icecast\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"listeners\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"example-host\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> filter(fn: (r) => r[\"mount\"] == \"/radiorucphen.aac\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "zuidwest.mp3",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 21 },
   "targets": [
    {
     "query": "from(bucket: \"icecast\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"listeners\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"example-host\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> filter(fn: (r) => r[\"mount\"] == \"/zuidwest.mp3\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "zuidwest.aac",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 21 },
   "targets": [
    {
     "query": "from(bucket: \"icecast\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"listeners\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"example-host\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> filter(fn: (r) => r[\"mount\"] == \"/zuidwest.aac\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "zuidwest.stl",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 6, "y": 30 },
   "targets": [
    {
     "query": "from(bucket: \"icecast\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"listeners\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"example-host\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\r\n  |> filter(fn: (r) => r[\"mount\"] == \"/zuidwest.stl\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  }
 ]
}